config/routes.rb
Midapt::Application.routes.draw do

  apipie #doc restful

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  devise_for :users

  #resources :interests
  #resources :mind_streams
  #resources :marks
  resources :streams
  resources :minds do
    resources :comments
    resources :marks
  end
  resources :users

  root 'home#index'
  
  get '/my/minds', to: 'minds#user_index'
end

app/models/mark.rb
class Mark < ActiveRecord::Base
	belongs_to :user
	belongs_to :markable, polymorphic: true

  validates :mark, inclusion: {in: [-1, 1]}
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_filter :authenticate_user!, only: [:create] # Device
  before_action :set_mark, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource param_method: :mark_params

  def index
    @marks = Mark.all
  end

  def show
  end

  def new
    @mark = Mark.new
  end

  def edit
  end

  def create
    @markable = find_markable
    if @markable.nil?
      render_404
    else
      @existing_mark = Mark.where('markable_id = ? and user_id = ?', @markable.id, current_user.id)
      if @existing_mark.empty?
        @mark = Mark.new(params[:mark].permit(:mark))
        @mark.markable = @markable
        @mark.user = current_user
        if @mark.save
          redirect_to polymorphic_path(@markable)
        else
          flash[:error] = 'something went wrong'
          redirect_to polymorphic_path(@markable)
        end
      else
        flash[:alert] = 'you have already voted'
        redirect_to polymorphic_path(@markable)
      end

    end
  end

  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: 'User comment mark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url }
      format.json { head :no_content }
    end
  end

  private
  def set_mark
    @mark = Mark.find(params[:id])
  end

  def mark_params
    params.require(:mark).permit(:mark)
  end

  def find_markable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.where(id: value).first
      end
    end
  end
end

app/views/marks/_form.html.slim
= form_for(@mark) do |f|
  - if @mark.errors.any?
    #error_explanation
      h2
        = pluralize(@mark.errors.count, "error")
        | prohibited this mark from being saved:
      ul
        - @mark.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :mark
    br/
    = f.number_field :mark
  .actions
    = f.submit

app/views/marks/edit.html.slim
h1 Editing mark
= render 'form'
= link_to 'Show', @mark
| \
| \#{link_to 'Back', marks_path}

app/views/marks/index.html.slim
h1 Listing marks
table
  thead
    tr
      th Mark
      th
      th
      th
  tbody
    - @marks.each do |mark|
      tr
        td= mark.mark
        td= link_to 'Show', mark
        td= link_to 'Edit', edit_mark_path(mark)
        td= link_to 'Destroy', mark, method: :delete, data:   confirm: 'Are you sure?'  
br/
= link_to 'New User comment mark', new_mark_path

app/views/marks/new.html.slim
h1 New mark
= render 'form'
= link_to 'Back', marks_path

app/views/marks/show.html.slim
p#notice= notice
p
  strong Mark:
  = @mark.mark
= link_to 'Edit', edit_mark_path(@mark)
| \
| \#{link_to 'Back', marks_path}