config/routes.rb
Midapt::Application.routes.draw do

  apipie #doc restful

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  devise_for :users

  #resources :interests
  #resources :mind_streams
  #resources :marks
  resources :streams
  resources :minds do
    resources :comments
    resources :marks
  end
  resources :users

  root 'home#index'
  
  get '/my/minds', to: 'minds#user_index'
end

app/models/mind.rb
class Mind < ActiveRecord::Base
  belongs_to :user

  has_many 	:comments
  has_many 	:marks, as: :markable

  has_many :mind_streams, inverse_of: :mind, :dependent => :destroy
  has_many :streams, through: :mind_streams

  validates :title,
            length: {in: 5..100}, allow_blank: true

  validates :text,
            presence: true,
            length: {in: 5..1000}

  validates_with StreamsNamesValidator

  attr_writer :streams_names

  def streams_names
  	@streams_names ||= self.streams.nil? ? '' : self.streams.collect(&:name).join(' ')
  end

  def assign_streams
    new_names = @streams_names.split(' ')
    self.streams.each do |stream|
      self.streams.delete stream if new_names.index { |s| s == stream.name }.nil?
    end
    new_names.each do |stream_name|
      if self.streams.index { |s| s.name == stream_name }.nil?
        stream = Stream.where(name: stream_name).first
        self.streams.push(stream.nil? ? Stream.new(:name => stream_name) : stream)
      end
    end
  end

end

app/controllers/minds_controller.rb
class MindsController < ApplicationController
  prepend_before_action :set_mind, only: [:show, :edit, :update, :destroy]
  before_filter :increment_views, only: [:show]
  before_filter :authenticate_user!, only: [:user_index, :new, :create, :edit, :update] # Device

  load_and_authorize_resource param_method: :mind_params # CanCan


  def index
    @minds = Mind.all.includes :streams
  end

  def user_index
    @minds = current_user.minds.includes :streams
    render(action: 'index')
  end

  def show
    @mind
    @marks_sum = Mark.where(markable_id: @mind.id, markable_type: 'Mind').sum('mark')
    @has_voted = !(current_user.nil? || Mark.where(user_id: current_user.id, markable_id: @mind.id, markable_type: 'Mind').empty?)
  end

  def new
    @mind = current_user.minds.new
  end

  def edit
  end

  def create
    @mind = current_user.minds.new mind_params
    @mind.valid? ? save_and_notificate(mind: @mind, action: 'create') : render(action: 'new')
  end

  def update
    @mind.assign_attributes(mind_params)
    @mind.valid? ? save_and_notificate(mind: @mind, action: 'update') : render(action: 'edit')
  end

  def destroy
    @mind.destroy
    redirect_to minds_url
  end

  private

  def increment_views
    Mind.increment_counter(:views_count, @mind.id)
    @mind.reload
  end

  def set_mind
    render_404 unless @mind = Mind.where(id: params[:id]).includes(:streams, :comments).first
  end

  def mind_params
    params.require(:mind).permit(:title, :text, :streams_names)
  end

  def save_and_notificate(hash, mind=hash[:mind])
    mind.assign_streams
    mind.save
    if hash[:action] == 'update'
      redirect_to mind, notice: 'Mind was successfully updated.', action: 'index'
    elsif hash[:action] == 'create'
      redirect_to mind, notice: 'Mind was successfully created.', action: 'index'
    end
  end

end

app/helpers/minds_helper.rb
module MindsHelper

end

app/views/minds/_comments.html.slim
ul
- comments.each do |comment|
	' 
	li= comment.message
=link_to 'New comment', new_mind_comment_path(@mind)

app/views/minds/_form.html.slim
= simple_form_for @mind do |f|
  - if @mind.errors.any?
    #error_explanation
      h2
        = pluralize(@mind.errors.count, "error")
        | prohibited this mind from being saved:
      ul
        - @mind.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :title
    br
    = f.input :title, label: false
  .field
    = f.label :text
    br
    = f.input :text, label: false
  .field
    = f.label :streams_names
    br
    = f.input :streams_names, label: false


    = debug @mind  
    

  .actions
    = f.submit

app/views/minds/_mark.html.slim
div
  | Total marks:
  '
  = marks_sum
- if user_signed_in?
  - if has_voted
    | already voted
  - else
    = form_for [markable, Mark.new] do |f|
      = f.radio_button :mark, -1
      = f.label 'Dislike'
      = f.radio_button :mark, 1
      = f.label 'Like'
      = f.submit

app/views/minds/edit.html.slim
h1 Editing mind
= render 'form'
= link_to 'Show', @mind
'
= link_to 'Back', minds_path

app/views/minds/index.html.slim
h1 Listing minds
table
  thead
    tr
      th Title
      th Text
      th Streams
      th
      th
      th
  tbody
    - @minds.each do |mind|
      tr
        td= mind.title
        td= mind.text
        td= render partial: 'streams', locals: {streams: mind.streams}
        td= link_to 'Show', mind
        td= link_to 'Edit', edit_mind_path(mind)
        td= link_to 'Destroy', mind, method: :delete
br
= link_to 'New Mind', new_mind_path

app/views/minds/new.html.slim
h1 New mind
= render 'form'
= link_to 'Back', minds_path

app/views/minds/show.html.slim
p#notice= notice
p
  strong Title:
  = @mind.title
p
  strong Text:
  = @mind.text
p
  | Views:
  '
  = @mind.views_count
p
  = render partial: 'mark', locals: {markable: @mind, marks_sum: @marks_sum, has_voted: @has_voted}
p
  strong Streams:
  = render partial: 'streams', locals: {streams: @mind.streams}
p
  strong Comments: 
  = render partial: 'comments', locals: {comments: @mind.comments}

= debug @mind

= link_to 'Edit', edit_mind_path(@mind)
'
= link_to 'Back', minds_path