config/routes.rb
Midapt::Application.routes.draw do

  apipie #doc restful

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  devise_for :users

  #resources :interests
  #resources :mind_streams
  #resources :marks
  resources :streams
  resources :minds do
    resources :comments
    resources :marks
  end
  resources :users

  root 'home#index'
  
  get '/my/minds', to: 'minds#user_index'
end

app/models/stream.rb
class Stream < ActiveRecord::Base
	has_many	:marks, as: :markable

	has_many	:interests
	has_many	:users, through: :interests

	has_many	:mind_streams, :dependent => :destroy
	has_many	:minds, through: :mind_streams

	validates 	:name,
            	presence: true,
           		length: { minimum: 3, maximum: 30 }

end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  before_action :set_stream, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @streams = Stream.all
  end

  def show
  end

  def new
    @stream = Stream.new
  end

  def edit
  end

  def create
    @stream = Stream.new stream_params

    respond_to do |format|
      if @stream.save
        format.html { redirect_to @stream, notice: 'stream was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stream }
      else
        format.html { render action: 'new' }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @stream.update(stream_params)
        format.html { redirect_to @stream, notice: 'stream was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @stream.destroy
    respond_to do |format|
      format.html { redirect_to streams_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_stream
    @stream = Stream.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stream_params
    params.require(:stream).permit(:name)
  end
end

app/views/streams/_form.html.slim
= form_for(@stream) do |f|
  - if @stream.errors.any?
    #error_explanation
      h2
        = pluralize(@stream.errors.count, "error")
        | prohibited this tag from being saved:
      ul
        - @stream.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :name
    br/
    = f.text_field :name
  .actions
    = f.submit

app/views/streams/edit.html.slim
h1 Editing stream
= render 'form'
= link_to 'Show', @stream
' 
= link_to 'Back', streams_path

app/views/streams/index.html.slim
h1 Listing streams
table
  thead
    tr
      th Name
      th
      th
      th
  tbody
    - @streams.each do |stream|
      tr
        td= stream.name
        td= link_to 'Show', stream
        td= link_to 'Edit', edit_stream_path(stream)
        td= link_to 'Destroy', stream, method: :delete 
br/
= link_to 'New stream', new_stream_path

app/views/streams/new.html.slim
h1 New stream
= render 'form'
= link_to 'Back', streams_path

app/views/streams/show.html.slim
p#notice= notice
p
  strong Name:
  = @stream.name
= link_to 'Edit', edit_stream_path(@stream)
'  
| #{link_to 'Back', streams_path}