config/routes.rb
Midapt::Application.routes.draw do

  apipie #doc restful

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  devise_for :users

  #resources :interests
  #resources :mind_streams
  #resources :marks
  resources :streams
  resources :minds do
    resources :comments
    resources :marks
  end
  resources :users

  root 'home#index'
  
  get '/my/minds', to: 'minds#user_index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    stream = Stream.where(name: params[:search]).includes(:minds).first
    @minds = stream.minds unless stream.nil?
  end
end

app/views/home/_comments.html.slim
ul
- comments.each do |comment|
	' 
	li= comment.message
=link_to 'New comment', new_mind_comment_path(@mind)

app/views/home/_streams.html.slim
- streams.each do |stream|
	' 
	= stream.name

app/views/home/index.html.slim
h1 Welcome in Midapt!

form accept-charset="UTF-8" action="/" method="get"
  .field
    = link_to 'Streams', streams_path
    br
    input name="search" type="text" value="#{params[:search]}"
    input type="submit" value="Search"


- unless @minds.nil?
  table
    thead
      tr
        th Title
        th Text
        th Streams
        th
    tbody
      - @minds.each do |mind|
        tr
          td= mind.title
          td= mind.text
          td= mind.streams.nil? || mind.streams.length == 0 ? '' : mind.streams.collect(&:name).join(' ')
          td= link_to 'Show', mind
- else
  p Введите потоки, которые хотите прочитать 
br
= link_to 'New Mind', new_mind_path
' 
= link_to 'My Minds', my_minds_path if user_signed_in?